const colors = {
  light: {
    text: "#0E0A1E",
    tint: "#7C3AED",
    background: "#E9E8F1",
    foreground: "#0E0A1E",
    card: "#FFFFFF",
    cardForeground: "#0E0A1E",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE9FE",
    secondaryForeground: "#6D28D9",
    muted: "#F1EEFB",
    mutedForeground: "#6E6589",
    accent: "#DB2777",
    accentForeground: "#FFFFFF",
    electric: "#06B6D4",
    electricGlow: "#22D3EE",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E6E1F5",
    input: "#E6E1F5",
    safe: "#10B981",
    safeForeground: "#FFFFFF",
    safeLight: "#ECFDF5",
    warning: "#F59E0B",
    warningLight: "#FFFBEB",
    danger: "#EF4444",
    surface: "#EEEAF9",
    sos: "#F43F5E",
    sosForeground: "#FFFFFF",
    sosLight: "#FFF1F3",
    sosGlow: "#FB7185",
    circle: "#7C3AED",
    record: "#EF4444",
    recordGlow: "#F87171",
  },
  radius: 16,
};

export default colors;
